#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
LOGFILE="$DIR/cron.log"

pushd "$DIR" > /dev/null
source python-env/bin/activate
python manage.py runcrons >> "$LOGFILE"
popd > /dev/null
