# Generated by Django 2.2.3 on 2019-07-03 06:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
	migrations.CreateModel(
            name='EmailLoginURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('success_url', models.CharField(max_length=2024)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_in', models.DurationField(default=datetime.timedelta(days=2))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Underviser'), (1, 'Vært'), (2, 'Koordinator'), (3, 'Administrator'), (4, 'Fakultetsredaktør'), (5, 'Ingen')], default=0)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'brugerrolle',
                'verbose_name_plural': 'brugerroller',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_information', models.TextField(blank=True, default='', verbose_name='Yderligere information')),
                ('my_resources', models.ManyToManyField(blank=True, to='booking.Product', verbose_name='Mine tilbud')),
                ('organizationalunit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.OrganizationalUnit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.UserRole')),
            ],
        ),
        
    ]
