# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-02 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='additional_information',
            field=models.TextField(blank=True, default='', verbose_name='Yderligere information'),
        ),
    ]
