# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 14:16
from __future__ import unicode_literals

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("booking", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="product", name="search_index"),
        migrations.RemoveField(model_name="visit", name="search_index"),
        migrations.AddField(
            model_name="product",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="booking_vis_search__08b9a5_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="booking_pro_search__a39a69_gin"
            ),
        ),
    ]
