# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-02 11:37
from __future__ import unicode_literals

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models

import booking.utils


class Migration(migrations.Migration):

    dependencies = [("booking", "0002_auto_20190516_1616")]

    operations = [
        migrations.AlterField(
            model_name="eventtime",
            name="notes",
            field=models.TextField(
                blank=True, default="", verbose_name="Interne kommentarer"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="duration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("00:00", "00:00"),
                    ("00:15", "00:15"),
                    ("00:30", "00:30"),
                    ("00:45", "00:45"),
                    ("01:00", "01:00"),
                    ("01:15", "01:15"),
                    ("01:30", "01:30"),
                    ("01:45", "01:45"),
                    ("02:00", "02:00"),
                    ("02:15", "02:15"),
                    ("02:30", "02:30"),
                    ("02:45", "02:45"),
                    ("03:00", "03:00"),
                    ("03:15", "03:15"),
                    ("03:30", "03:30"),
                    ("03:45", "03:45"),
                    ("04:00", "04:00"),
                    ("04:15", "04:15"),
                    ("04:30", "04:30"),
                    ("04:45", "04:45"),
                    ("05:00", "05:00"),
                    ("05:15", "05:15"),
                    ("05:30", "05:30"),
                    ("05:45", "05:45"),
                    ("06:00", "06:00"),
                    ("06:15", "06:15"),
                    ("06:30", "06:30"),
                    ("06:45", "06:45"),
                    ("07:00", "07:00"),
                    ("07:15", "07:15"),
                    ("07:30", "07:30"),
                    ("07:45", "07:45"),
                    ("08:00", "08:00"),
                    ("08:15", "08:15"),
                    ("08:30", "08:30"),
                    ("08:45", "08:45"),
                    ("09:00", "09:00"),
                    ("09:15", "09:15"),
                    ("09:30", "09:30"),
                    ("09:45", "09:45"),
                    ("10:00", "10:00"),
                    ("10:15", "10:15"),
                    ("10:30", "10:30"),
                    ("10:45", "10:45"),
                    ("11:00", "11:00"),
                    ("11:15", "11:15"),
                    ("11:30", "11:30"),
                    ("11:45", "11:45"),
                ],
                max_length=8,
                null=True,
                verbose_name="Varighed",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="extra_search_text",
            field=models.TextField(
                blank=True,
                default="",
                editable=False,
                verbose_name="Tekst-værdier til fritekstsøgning",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="needed_hosts",
            field=models.IntegerField(
                choices=[
                    (None, "---------"),
                    (0, "Ingen"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (-10, "Mere end 10"),
                ],
                default=0,
                verbose_name="Nødvendigt antal værter",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="needed_teachers",
            field=models.IntegerField(
                choices=[
                    (None, "---------"),
                    (0, "Ingen"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (-10, "Mere end 10"),
                ],
                default=0,
                verbose_name="Nødvendigt antal undervisere",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="state",
            field=models.IntegerField(
                choices=[
                    (None, "---------"),
                    (0, "Under udarbejdelse"),
                    (1, "Offentlig"),
                    (2, "Skjult"),
                ],
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="resourcetype",
            name="plural",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="studymaterial",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=booking.utils.CustomStorage(),
                upload_to="material",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="comments",
            field=models.TextField(
                blank=True, default="", verbose_name="Interne kommentarer"
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="extra_search_text",
            field=models.TextField(
                blank=True,
                default="",
                editable=False,
                verbose_name="Tekst-værdier til fritekstsøgning",
            ),
        ),
    ]
