# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-24 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190702_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='deprecated_bookable',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='deprecated_end_datetime',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='deprecated_product',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='deprecated_start_datetime',
        ),
    ]
