# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("booking", "0003_sprint4_post_regions")]

    def populate_schools(apps, schema_editor):
        from booking.models import School as school
        from booking.models import PostCode
        db_alias = schema_editor.connection.alias

        school.objects.using(db_alias).bulk_create([
            school(name=u"Aabenraa Statsskole", postcode=PostCode.objects.get(number=6200)),
            school(name=u"Aalborg Katedralskole", postcode=PostCode.objects.get(number=9000)),
            school(name=u"Aalborg Tekniske Gymnasium", postcode=PostCode.objects.get(number=9000)),
            school(name=u"Aalborghus Gymnasium", postcode=PostCode.objects.get(number=9000)),
            school(name=u"Allerød Gymnasium", postcode=PostCode.objects.get(number=3450)),
            school(name=u"Aurehøj Gymnasium", postcode=PostCode.objects.get(number=2820)),
            school(name=u"Bagsværd Kostskole og Gymnasium", postcode=PostCode.objects.get(number=2880)),
            school(name=u"Birkerød Gymnasium, HF, IB & Kostskole", postcode=PostCode.objects.get(number=3460)),
            school(name=u"Bjerringbro Gymnasium", postcode=PostCode.objects.get(number=8850)),
            school(name=u"Borupgaard Gymnasium", postcode=PostCode.objects.get(number=2750)),
            school(name=u"Brøndby Gymnasium", postcode=PostCode.objects.get(number=2605)),
            school(name=u"Brønderslev Gymnasium og HF", postcode=PostCode.objects.get(number=9700)),
            school(name=u"Campus Bornholm", postcode=PostCode.objects.get(number=3700)),
            school(name=u"Campus Vejle - Handelsgymnasiet", postcode=PostCode.objects.get(number=7100)),
            school(name=u"CELF - Handelsgymnasiet i Nakskov", postcode=PostCode.objects.get(number=4900)),
            school(name=u"CELF - Handelsgymnasiet i Nykøbing", postcode=PostCode.objects.get(number=4800)),
            school(name=u"Christianshavns Gymnasium", postcode=PostCode.objects.get(number=1422)),
            school(name=u"CPH WEST - Albertslund Gymnasium", postcode=PostCode.objects.get(number=2620)),
            school(name=u"CPH WEST - Handelsgymnasiet i Ballerup", postcode=PostCode.objects.get(number=2750)),
            school(name=u"CPH WEST - Handelsgymnasiet i Ishøj", postcode=PostCode.objects.get(number=2650)),
            school(name=u"CPH WEST - Ishøj Gymnasium", postcode=PostCode.objects.get(number=2650)),
            school(name=u"Det Frie Gymnasium", postcode=PostCode.objects.get(number=2200)),
            school(name=u"Dronninglund Gymnasium", postcode=PostCode.objects.get(number=9330)),
            school(name=u"Egaa Gymnasium", postcode=PostCode.objects.get(number=8250)),
            school(name=u"Egedal Gymnasium & HF", postcode=PostCode.objects.get(number=3660)),
            school(name=u"Erhvervsgymnasiet Grindsted", postcode=PostCode.objects.get(number=7200)),
            school(name=u"Erhvervsskolen Nordsjælland ", postcode=PostCode.objects.get(number=3400)),
            school(name=u"Esbjerg Gymnasium", postcode=PostCode.objects.get(number=6705)),
            school(name=u"Espergærde Gymnasium og HF", postcode=PostCode.objects.get(number=3060)),
            school(name=u"EUC Nordvestsjælland", postcode=PostCode.objects.get(number=4300)),
            school(name=u"EUC-Nord, HTX, Hjørring", postcode=PostCode.objects.get(number=9800)),
            school(name=u"Faaborg Gymnasium", postcode=PostCode.objects.get(number=5600)),
            school(name=u"Falkonergårdens Gymnasium og HF", postcode=PostCode.objects.get(number=2000)),
            school(name=u"Favrskov Gymnasium", postcode=PostCode.objects.get(number=8370)),
            school(name=u"Fjerritslev Gymnasium", postcode=PostCode.objects.get(number=7000)),
            school(name=u"Fredericia Gymnasium", postcode=PostCode.objects.get(number=7000)),
            school(name=u"Frederiksberg Gymnasium", postcode=PostCode.objects.get(number=9690)),
            school(name=u"Frederiksberg Tekniske Gymnasium", postcode=PostCode.objects.get(number=1974)),
            school(name=u"Frederiksborg Gymnasium & HF", postcode=PostCode.objects.get(number=3400)),
            school(name=u"Frederikshavn Gymnasium og HF", postcode=PostCode.objects.get(number=9900)),
            school(name=u"Frederikssund Gymnasium", postcode=PostCode.objects.get(number=3600)),
            school(name=u"Frederiksværk Gymnasium & HF", postcode=PostCode.objects.get(number=3300)),
            school(name=u"Gefion Gymnasium", postcode=PostCode.objects.get(number=1350)),
            school(name=u"Gladsaxe Gymnasium", postcode=PostCode.objects.get(number=2860)),
            school(name=u"Gl. Hellerup Gymnasium", postcode=PostCode.objects.get(number=2900)),
            school(name=u"Grenå Gymnasium", postcode=PostCode.objects.get(number=8500)),
            school(name=u"Greve Gymnasium", postcode=PostCode.objects.get(number=2670)),
            school(name=u"Gribskov Gymnasium", postcode=PostCode.objects.get(number=3200)),
            school(name=u"Grindsted Gymnasium & HF", postcode=PostCode.objects.get(number=7200)),
            school(name=u"Haderslev Gymnasium", postcode=PostCode.objects.get(number=6100)),
            school(name=u"Handelsgymnasiet - Århus Købmandsskole Risskov", postcode=PostCode.objects.get(number=8240)),
            school(name=u"Handelsgymnasiet - Århus Købmandsskole Viby", postcode=PostCode.objects.get(number=8260)),
            school(name=u"Hasseris Gymnasium", postcode=PostCode.objects.get(number=9000)),
            school(name=u"Helsingør Gymnasium", postcode=PostCode.objects.get(number=3000)),
            school(name=u"Herlev Gymnasium & HF", postcode=PostCode.objects.get(number=2730)),
            school(name=u"Herlufsholm Skole", postcode=PostCode.objects.get(number=4700)),
            school(name=u"Herning Gymnasium", postcode=PostCode.objects.get(number=7400)),
            school(name=u"Herningsholm Gymnasium", postcode=PostCode.objects.get(number=7400)),
            school(name=u"Himmelev Gymnasium", postcode=PostCode.objects.get(number=4000)),
            school(name=u"Hjørring Gymnasium og HF", postcode=PostCode.objects.get(number=9800)),
            school(name=u"Holstebro Gymnasium & HF", postcode=PostCode.objects.get(number=7500)),
            school(name=u"Horsens Gymnasium", postcode=PostCode.objects.get(number=8700)),
            school(name=u"Horsens Statsskole", postcode=PostCode.objects.get(number=8700)),
            school(name=u"HTX Hillerød, Erhvervsskolen Nordsjælland", postcode=PostCode.objects.get(number=3400)),
            school(name=u"Hvidovre Gymnasium", postcode=PostCode.objects.get(number=2650)),
            school(name=u"Høje-Taastrup Gymnasium", postcode=PostCode.objects.get(number=2630)),
            school(name=u"Høng Gymnasium & HF", postcode=PostCode.objects.get(number=4270)),
            school(name=u"Ikast-Brande Gymnasium", postcode=PostCode.objects.get(number=7430)),
            school(name=u"Ingrid Jespersens Gymnasieskole", postcode=PostCode.objects.get(number=2100)),
            school(name=u"Kalundborg Gymnasium & HF", postcode=PostCode.objects.get(number=4400)),
            school(name=u"Kolding Gymnasium", postcode=PostCode.objects.get(number=6000)),
            school(name=u"Københavns Tekniske Gymnasium", postcode=PostCode.objects.get(number=2400)),
            school(name=u"København Nord - HHX Frederikssund", postcode=PostCode.objects.get(number=3600)),
            school(name=u"København Nord - HHX Hillerød", postcode=PostCode.objects.get(number=3400)),
            school(name=u"København Nord - HHX Lyngby", postcode=PostCode.objects.get(number=2800)),
            school(name=u"Køge Gymnasium", postcode=PostCode.objects.get(number=4600)),
            school(name=u"Køge Handelsskole ", postcode=PostCode.objects.get(number=4600)),
            school(name=u"Langkær Gymnasium", postcode=PostCode.objects.get(number=8381)),
            school(name=u"Lemvig Gymnasium", postcode=PostCode.objects.get(number=7620)),
            school(name=u"Lyngby Gymnasium", postcode=PostCode.objects.get(number=2800)),
            school(name=u"Lyngby Tekniske Gymnasium", postcode=PostCode.objects.get(number=2800)),
            school(name=u"Mariagerfjord Gymnasium", postcode=PostCode.objects.get(number=9500)),
            school(name=u"Maribo Gymnasium", postcode=PostCode.objects.get(number=4930)),
            school(name=u"Marie Kruses Skole", postcode=PostCode.objects.get(number=3520)),
            school(name=u"Marselisborg Gymnasium", postcode=PostCode.objects.get(number=8000)),
            school(name=u"Middelfart Gymnasium", postcode=PostCode.objects.get(number=5500)),
            school(name=u"Midtfyns Gymnasium", postcode=PostCode.objects.get(number=5750)),
            school(name=u"Midtsjællands Gymnasieskoler", postcode=PostCode.objects.get(number=4100)),
            school(name=u"Morsø Gymnasium", postcode=PostCode.objects.get(number=7900)),
            school(name=u"Mulernes Legatskole", postcode=PostCode.objects.get(number=5240)),
            school(name=u"Munkensdam Gymnasium", postcode=PostCode.objects.get(number=6000)),
            school(name=u"Nakskov Gymnasium", postcode=PostCode.objects.get(number=4900)),
            school(name=u"N. Zahles Gymnasieskole", postcode=PostCode.objects.get(number=1358)),
            school(name=u"Niels Brock Elitegymnasiet", postcode=PostCode.objects.get(number=1115)),
            school(name=u"Niels Steensens Gymnasium", postcode=PostCode.objects.get(number=2100)),
            school(name=u"Nordfyns Gymnasium", postcode=PostCode.objects.get(number=5471)),
            school(name=u"Nordsjællands Grundskole & Gymnasium", postcode=PostCode.objects.get(number=2970)),
            school(name=u"Nyborg Gymnasium", postcode=PostCode.objects.get(number=5800)),
            school(name=u"Nykøbing Katedralskole", postcode=PostCode.objects.get(number=4800)),
            school(name=u"Nærum Gymnasium", postcode=PostCode.objects.get(number=2850)),
            school(name=u"Næstved Gymnasium & HF", postcode=PostCode.objects.get(number=4700)),
            school(name=u"Nørre Gymnasium", postcode=PostCode.objects.get(number=2700)),
            school(name=u"Nørresundby Gymnasium & HF", postcode=PostCode.objects.get(number=9400)),
            school(name=u"Odder Gymnasium", postcode=PostCode.objects.get(number=8300)),
            school(name=u"Odense Katedralskole", postcode=PostCode.objects.get(number=5000)),
            school(name=u"Odense Tekniske Gymnasium", postcode=PostCode.objects.get(number=5230)),
            school(name=u"Odsherreds Gymnasium", postcode=PostCode.objects.get(number=4550)),
            school(name=u"Ordrup Gymnasium", postcode=PostCode.objects.get(number=2920)),
            school(name=u"Paderup Gymnasium", postcode=PostCode.objects.get(number=8960)),
            school(name=u"Randers Statsskole", postcode=PostCode.objects.get(number=8900)),
            school(name=u"Ribe Katedralskole", postcode=PostCode.objects.get(number=6760)),
            school(name=u"Ringkjøbing Gymnasium", postcode=PostCode.objects.get(number=6950)),
            school(name=u"Risskov Gymnasium", postcode=PostCode.objects.get(number=8240)),
            school(name=u"Rosborg Gymnasium & HF", postcode=PostCode.objects.get(number=7100)),
            school(name=u"Roskilde Gymnasium", postcode=PostCode.objects.get(number=4000)),
            school(name=u"Roskilde Handelsskole", postcode=PostCode.objects.get(number=4000)),
            school(name=u"Roskilde Katedralskole", postcode=PostCode.objects.get(number=4000)),
            school(name=u"Roskilde Tekniske Gymnasium", postcode=PostCode.objects.get(number=4000)),
            school(name=u"Rungsted Gymnasium", postcode=PostCode.objects.get(number=2960)),
            school(name=u"Rybners Gymnasium HHX", postcode=PostCode.objects.get(number=6700)),
            school(name=u"Rybners Gymnasium STX", postcode=PostCode.objects.get(number=6700)),
            school(name=u"Rysensteen Gymnasium", postcode=PostCode.objects.get(number=1704)),
            school(name=u"Rødkilde Gymnasium", postcode=PostCode.objects.get(number=7100)),
            school(name=u"Rødovre Gymnasium", postcode=PostCode.objects.get(number=2610)),
            school(name=u"Rønde Gymnasium", postcode=PostCode.objects.get(number=8410)),
            school(name=u"Sankt Annæ Gymnasium", postcode=PostCode.objects.get(number=2500)),
            school(name=u"Sct. Knuds Gymnasium", postcode=PostCode.objects.get(number=5230)),
            school(name=u"Selandia-CEU", postcode=PostCode.objects.get(number=4200)),
            school(name=u"Silkeborg Gymnasium", postcode=PostCode.objects.get(number=8600)),
            school(name=u"Skanderborg Gymnasium", postcode=PostCode.objects.get(number=8660)),
            school(name=u"Skanderborg-Odder Center for Uddannelse", postcode=PostCode.objects.get(number=8660)),
            school(name=u"Skive Gymnasium og HF", postcode=PostCode.objects.get(number=7800)),
            school(name=u"Slagelse Gymnasium", postcode=PostCode.objects.get(number=4200)),
            school(name=u"Solrød Gymnasium", postcode=PostCode.objects.get(number=2680)),
            school(name=u"Sorø Akademis Skole", postcode=PostCode.objects.get(number=4180)),
            school(name=u"Stenhus Gymnasium & HF", postcode=PostCode.objects.get(number=4300)),
            school(name=u"Struer Statsgymnasium", postcode=PostCode.objects.get(number=7600)),
            school(name=u"Støvring Gymnasium", postcode=PostCode.objects.get(number=9530)),
            school(name=u"Svendborg Gymnasium og HF", postcode=PostCode.objects.get(number=5700)),
            school(name=u"Svendborg Tekniske Gymnasium (Svendborg Erhvervsskole)", postcode=PostCode.objects.get(number=5700)),
            school(name=u"Sønderborg Statsskole", postcode=PostCode.objects.get(number=6400)),
            school(name=u"Teknisk Gymnasium Skanderborg", postcode=PostCode.objects.get(number=8660)),
            school(name=u"Teknisk Gymnasium Viby", postcode=PostCode.objects.get(number=8260)),
            school(name=u"Thisted Gymnasium & HF", postcode=PostCode.objects.get(number=7700)),
            school(name=u"Tornbjerg Gymnasium", postcode=PostCode.objects.get(number=5220)),
            school(name=u"Tønder Gymnasium", postcode=PostCode.objects.get(number=6270)),
            school(name=u"Tørring Gymnasium", postcode=PostCode.objects.get(number=7160)),
            school(name=u"Tårnby Gymnasium & HF", postcode=PostCode.objects.get(number=2770)),
            school(name=u"Varde Gymnasium", postcode=PostCode.objects.get(number=6800)),
            school(name=u"Vejen Gymnasium & HF", postcode=PostCode.objects.get(number=6600)),
            school(name=u"Vejle Tekniske Gymnasium", postcode=PostCode.objects.get(number=7100)),
            school(name=u"Vestfyns Gymnasium", postcode=PostCode.objects.get(number=5620)),
            school(name=u"Vesthimmerlands Gymnasium og HF", postcode=PostCode.objects.get(number=9600)),
            school(name=u"Vestjysk Gymnasium", postcode=PostCode.objects.get(number=6880)),
            school(name=u"Viborg Gymnasium & HF", postcode=PostCode.objects.get(number=8800)),
            school(name=u"Viborg Katedralskole", postcode=PostCode.objects.get(number=8800)),
            school(name=u"Viborg Handelsgymnasium", postcode=PostCode.objects.get(number=8800)),
            school(name=u"Viby Gymnasium", postcode=PostCode.objects.get(number=8260)),
            school(name=u"Virum Gymnasium", postcode=PostCode.objects.get(number=2830)),
            school(name=u"Vordingborg Gymnasium og HF", postcode=PostCode.objects.get(number=4760)),
            school(name=u"VUC Aarhus", postcode=PostCode.objects.get(number=8000)),
            school(name=u"ZBC - Handelsgymnasiet Næstved", postcode=PostCode.objects.get(number=4700)),
            school(name=u"ZBC - Handelsgymnasiet Ringsted", postcode=PostCode.objects.get(number=4100)),
            school(name=u"ZBC - Handelsgymnasiet Vordingborg", postcode=PostCode.objects.get(number=4760)),
            school(name=u"Øregård Gymnasium", postcode=PostCode.objects.get(number=2900)),
            school(name=u"Ørestad Gymnasium", postcode=PostCode.objects.get(number=2300)),
            school(name=u"Århus Akademi", postcode=PostCode.objects.get(number=8200)),
            school(name=u"Aarhus Gymnasium", postcode=PostCode.objects.get(number=8000)),
            school(name=u"Aarhus Katedralskole", postcode=PostCode.objects.get(number=8000)),
            school(name=u"Aarhus Statsgymnasium", postcode=PostCode.objects.get(number=8210))
        ])

    operations = [
        migrations.CreateModel(
                name='School',
                fields=[
                    ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                    ('name', models.CharField(max_length=128)),
                    ('postcode', models.ForeignKey(to='booking.PostCode', null=True)),
                ],
        ),
        migrations.RunPython(populate_schools),
    ]
