# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-24 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("booking", "0004_auto_20190724_1332")]

    operations = [
        migrations.AlterModelOptions(
            name="objectstatistics",
            options={"verbose_name_plural": "object statistics"},
        )
    ]
