# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-10 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20190724_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_multiproductvisit',
            field=models.BooleanField(default=False),
        ),
    ]
