# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-10-30 09:55
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20200821_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostresource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bruger'),
        ),
        migrations.AlterField(
            model_name='product',
            name='booking_close_days_before',
            field=models.IntegerField(default=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Antal dage før afholdelse, hvor der lukkes for tilmeldinger'),
        ),
        migrations.AlterField(
            model_name='product',
            name='booking_max_days_in_future',
            field=models.PositiveIntegerField(default=90, null=True, verbose_name='Maksimalt antal dage i fremtiden hvor der kan tilmeldes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='maximum_number_of_visitors',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Højeste antal deltagere'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_number_of_visitors',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mindste antal deltagere'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pris'),
        ),
        migrations.AlterField(
            model_name='product',
            name='waiting_list_deadline_days',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lukning af venteliste (dage inden besøg)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='waiting_list_deadline_hours',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Lukning af venteliste (timer inden besøg)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='waiting_list_length',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Antal pladser'),
        ),
        migrations.AlterField(
            model_name='teacherresource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bruger'),
        ),
    ]
